export const possibleSpaces = [
        'Tree lighting',
        'Old flame',
        'Small town',
        'Visible whipped cream on holiday drink',
        'Classic tan plaid Scotland scarf',
        'Animal dressed Christmassy',
        'More than one wreath in background of scene',
        'Oversize ornaments',
        'Kissing under mistletoe',
        'A change of heart',
        'Job offer/Promotion',
        'Magically starts snowing',
        'Snow globe',
        'Skating',
        'Toboganning',
        'Protagonists sing Christmas carols',
        'Christmas concert',
        'Sitting around fireplace',
        'Stormed in',
        'Buy Christmas tree',
        'Make cookies',
        'Gingerbread',
        'Interrupted travel plans',
        'Parent interfering with love life',
        'Annual holiday party',
        'Single parent',
        'Child hungry',
        'Child lost',
        'Enters contest',
        'Turkey dinner',
        'Workaholic',
        '"This might be crazy but..."',
        '"It\'s not Christmas without..."',
        'Throwing snowballs',
        'Charity event',
        'Volunteering at an event',
        'Marriage proposal',
        'Dancing',
        'Two different love interests',
        'Christmas sweater with pattern around the neck',
        'Clashing people team up',
        'Falling on ice',
        'Homemade ornament',
        'Talking to animals',
        'Grand gesture',
        'Apologize for a hug/kiss',
        'Couple runs into each other',
        'White toque',
        'City person struggles with snow',
        'Everyone to the airport/station!'
]