export const possibleSpaces = [
        'Tree lighting',
        'Old flame',
        'Small town',
        'Drinking from an empty cup',
        'Plaid',
        'Animal dressed Christmassy',
        'More than one wreath in background',
        'Oversize ornaments',
        'A change of heart',
        'Job offer/Promotion',
        'Magically starts snowing',
        'Snow globe',
        'Skating',
        'Toboganning',
        'Christmas carols',
        'Christmas concert',
        'Sitting around fireplace',
        'Stormed in',
        'Real tree for Christmas tree',
        'Make cookies',
        'Gingerbread',
        'Interrupted travel plans',
        'Parent interfering with love life',
        'Annual holiday party',
        'Single parent',
        'Child lost',
        'Enters contest',
        'Turkey dinner',
        'Workaholic',
        'This might be crazy but...',
        'It\'s not Christmas without...',
        'Throwing snowballs',
        'Charity event',
        'Volunteering at an event',
        'Marriage proposal',
        'Dancing',
        'Two different love interests',
        'Christmas sweater',
        'Clashing people team up',
        'Falling on ice',
        'Homemade ornament',
        'Talking to animals',
        'Grand gesture',
        'Apologize for a hug/kiss',
        'Couple runs into each other',
        'White toque',
        'City person struggles with snow',
        'Everyone to the ...!',
        'Almost kiss',
        'Writer/journalist',
        'Horse/wagon/carriage ride',
        'Breakup',
        'Build a snowman',
        'Breakfast',
        'Inn or lodge (not hotel)',
        'Sketchy economics',
        'Christmas festival/market',
        'Coffee shop/bakery',
        'Pointsetta',
]